// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzjwkentllirumevvmhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6andrZW50bGxpcnVtZXZ2bWhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0OTY4MDQsImV4cCI6MjA1OTA3MjgwNH0.Z8v_Hf_Q9sJ4JsyXYxIg0aOJDiwmQo6pgw3L2uJwtCU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);